// subjects/polaris/src/views/HomeView.tsx
import { motion } from "motion/react";
import { ArrowUpRight, Flag } from "lucide-react";
import type { Catalog } from "@/content/catalog";
import { BALANCES, LENSES, routeMatrix, routeNodeCount } from "@/content/routes";
import type { Route } from "@/content/types";
import { useApp } from "@/state/store";
import { BALANCE_LABEL, LENS_HINT, LENS_LABEL, balanceVar } from "@/ui/labels";

function RouteCard({ route, index }: { route: Route; index: number }) {
  const go = useApp((s) => s.go);
  return (
    <motion.button
      type="button"
      initial={{ opacity: 0, y: 14 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ delay: 0.05 * index, duration: 0.4, ease: [0.2, 0.7, 0.2, 1] }}
      onClick={() => go({ view: "route", routeId: route.id })}
      className="group relative flex flex-col overflow-hidden rounded-2xl border border-line bg-surface p-4 text-left shadow-[var(--shadow-card)] transition-[transform,box-shadow,border-color] duration-200 hover:-translate-y-1 hover:border-accent hover:shadow-[var(--shadow-lift)]"
    >
      <span className="absolute inset-x-0 top-0 h-1" style={{ background: balanceVar(route.balance) }} />
      <span className="flex items-start gap-2">
        <span className="flex-1 text-[15.5px] font-semibold leading-snug">{route.title}</span>
        <ArrowUpRight size={16} className="mt-0.5 shrink-0 text-faint transition-colors group-hover:text-accent" />
      </span>
      <span className="mt-1.5 line-clamp-3 text-[12.5px] leading-relaxed text-muted">{route.summary}</span>
      <span className="mt-3 flex items-start gap-1.5 rounded-lg bg-surface-2/70 p-2 text-[12px] leading-snug">
        <Flag size={12} className="mt-0.5 shrink-0 text-gold" fill="currentColor" />
        <span className="line-clamp-2">{route.artifact}</span>
      </span>
      <span className="mt-3 flex items-center gap-2 text-[11.5px] text-faint">
        <span>{route.stages.length} 个阶段</span>·<span>{routeNodeCount(route)} 个知识点</span>
      </span>
    </motion.button>
  );
}

export function HomeView({ catalog }: { catalog: Catalog }) {
  const go = useApp((s) => s.go);
  const matrix = routeMatrix(catalog);
  const codesign = catalog.allMaps.find((map) => map.view_kind === "codesign");
  let counter = 0;

  return (
    <div className="h-full overflow-y-auto">
      <div className="mx-auto max-w-[1280px] px-8 pb-16 pt-9">
        <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }}>
          <h1 className="text-[34px] font-bold leading-tight tracking-tight">
            同一块知识底盘，<span className="text-accent">走出不同的路线</span>
          </h1>
          <p className="mt-2 max-w-[760px] text-[15px] leading-relaxed text-muted">
            先选一个角度和技术方向，沿它的阶段走下去；每条路线都有一个能检查的终点产物。
            软硬结合是主线——软件看见的硬件、硬件承诺给软件的东西，被当作一等知识来讲。
          </p>
          <div className="mt-4 flex flex-wrap gap-2 text-[12.5px] text-muted">
            <span className="rounded-full bg-surface px-3 py-1 shadow-[var(--shadow-card)]">{catalog.routes.length} 条路线</span>
            <span className="rounded-full bg-surface px-3 py-1 shadow-[var(--shadow-card)]">
              {catalog.maps.reduce((sum, map) => sum + map.nodes.length, 0)} 个知识点在底盘里
            </span>
            {codesign && (
              <button
                type="button"
                onClick={() => go({ view: "base", mapId: codesign.id })}
                className="rounded-full bg-accent-soft px-3 py-1 font-medium text-accent transition-colors hover:bg-accent hover:text-accent-ink"
              >
                {codesign.nodes.length} 个软硬接口节点 →
              </button>
            )}
          </div>
        </motion.div>

        {/* 软硬权重轴：路线按「偏软件 ↔ 偏硬件」放在三列里，行是划分角度 */}
        <div className="mt-9 grid grid-cols-[168px_repeat(3,minmax(0,1fr))] gap-x-5 gap-y-5">
          <div />
          {BALANCES.map((balance) => (
            <div key={balance} className="flex flex-col gap-2">
              <span className="text-[13px] font-semibold" style={{ color: balanceVar(balance) }}>
                {BALANCE_LABEL[balance]}
              </span>
              <span
                className="h-1.5 rounded-full"
                style={{ background: `linear-gradient(90deg, ${balanceVar(balance)}, color-mix(in srgb, ${balanceVar(balance)} 25%, transparent))` }}
              />
            </div>
          ))}

          {LENSES.map((lens) => (
            <div key={lens} className="contents">
              <div className="pt-1">
                <div className="text-[14px] font-semibold">{LENS_LABEL[lens]}</div>
                <p className="mt-1 text-[12px] leading-snug text-muted">{LENS_HINT[lens]}</p>
              </div>
              {BALANCES.map((balance) => {
                const routes = matrix[lens][balance];
                return (
                  <div key={balance} className="flex flex-col gap-3">
                    {routes.length === 0 ? (
                      <div className="grid min-h-[72px] place-items-center rounded-2xl border border-dashed border-line text-[12px] text-faint">
                        这里还没有路线
                      </div>
                    ) : (
                      routes.map((route) => <RouteCard key={route.id} route={route} index={counter++} />)
                    )}
                  </div>
                );
              })}
            </div>
          ))}
        </div>

        <h2 className="mb-3 mt-12 text-[15px] font-semibold">想直接看全景？底盘里的图</h2>
        <div className="flex flex-wrap gap-2.5">
          {catalog.maps.map((map) => (
            <button
              key={map.id}
              type="button"
              onClick={() => go({ view: "base", mapId: map.id })}
              className="rounded-xl border border-line bg-surface px-4 py-2.5 text-left text-[13px] transition-[border-color,box-shadow] hover:border-accent hover:shadow-[var(--shadow-card)]"
            >
              <span className="font-medium">{map.title}</span>
              <span className="ml-2 text-faint">{map.nodes.length} 个</span>
            </button>
          ))}
        </div>
      </div>
    </div>
  );
}

// subjects/esd/src/views/HomeView.vue
<script setup lang="ts">
// 首页:考试事实、续读、课程总览与真题/战况入口。
import { onMounted, ref } from "vue";
import { motion } from "motion-v";
import { ArrowRight, ScrollText, Gauge, Target, CalendarClock, BookOpen } from "lucide-vue-next";
import { course, allSections, masteryOf } from "../content";
import { attemptsSummary, loadSetting } from "../db";
import type { KpSummary } from "../types";
import { GradeBadge } from "../components/ui";
import ProgressRing from "../components/ProgressRing.vue";
import type { View } from "./types";

interface LastRead {
  sectionId: string;
  chapterTitle: string;
  sectionTitle: string;
}

const props = defineProps<{ go: (v: View) => void }>();
const go = props.go;

const summary = ref<KpSummary[]>([]);
const last = ref<LastRead | null>(null);
onMounted(() => {
  attemptsSummary().then((s) => (summary.value = s)).catch(() => {});
  loadSetting("last-read")
    .then((v) => {
      if (v) {
        const parsed = JSON.parse(v) as LastRead;
        // 只在节还存在时展示续读(内容重组后旧位置自然失效)
        if (allSections().some((s) => s.section.id === parsed.sectionId)) last.value = parsed;
      }
    })
    .catch(() => {});
});

const sections = course.chapters.flatMap((ch) => ch.sections);
const graded = sections.filter((s) => s.kp);
const avg = graded.length
  ? graded.reduce((acc, s) => acc + masteryOf(s.kp!.id, summary.value), 0) / graded.length
  : 0;
const done = graded.filter((s) => masteryOf(s.kp!.id, summary.value) >= 0.6).length;
</script>

<template>
  <div class="space-y-8">
    <!-- hero -->
    <section class="pb-8 pt-4">
      <motion.div :initial="{ opacity: 0, y: 14 }" :animate="{ opacity: 1, y: 0 }" :transition="{ duration: 0.5 }">
        <div class="flex flex-wrap items-center gap-2">
          <span class="rounded-full accent-gradient px-3 py-1 text-[12px] font-bold text-white shadow">
            {{ course.exam.subject }}
          </span>
          <span
            class="inline-flex items-center gap-1 rounded-full px-3 py-1 text-[12px] font-medium ring-1"
            style="background: var(--tk-surface); color: var(--tk-muted); border-color: var(--tk-line)"
          >
            <Target :size="12" /> {{ course.exam.score_range }}
          </span>
          <span
            class="inline-flex items-center gap-1 rounded-full px-3 py-1 text-[12px] font-medium ring-1"
            style="background: var(--tk-surface); color: var(--tk-muted); border-color: var(--tk-line)"
          >
            <CalendarClock :size="12" /> 一年一考,2024 年起为 5 月底
          </span>
        </div>
        <h1 class="tk-display mt-4 text-[32px] font-bold leading-snug tracking-tight">
          考纲对齐、分值驱动的
          <span class="text-gradient">嵌入式备考</span>
        </h1>
        <p class="mt-2 max-w-3xl text-[15px] leading-relaxed" style="color: var(--tk-muted)">
          {{ course.exam.note }}
        </p>
      </motion.div>
    </section>

    <!-- 续读 -->
    <motion.button
      v-if="last"
      type="button"
      :initial="{ opacity: 0, y: -8 }"
      :animate="{ opacity: 1, y: 0 }"
      class="tk-card tk-card-hover flex w-full items-center gap-3 px-5 py-3.5 text-left"
      @click="go({ kind: 'topic', sectionId: last.sectionId })"
    >
      <span class="flex h-9 w-9 items-center justify-center rounded-xl accent-gradient text-white shadow">
        <BookOpen :size="17" />
      </span>
      <span class="flex-1 text-[14px]">
        <span class="font-semibold">接着学</span>
        <span class="ml-2" style="color: var(--tk-muted)">{{ last.chapterTitle }} · {{ last.sectionTitle }}</span>
      </span>
      <ArrowRight :size="16" class="accent-fg" />
    </motion.button>

    <!-- 课程卡 -->
    <section>
      <motion.button
        type="button"
        :initial="{ opacity: 0, y: 18 }"
        :animate="{ opacity: 1, y: 0 }"
        :transition="{ delay: 0.08, duration: 0.45 }"
        class="tk-card tk-card-hover group relative w-full overflow-hidden p-6 text-left"
        @click="go({ kind: 'course' })"
      >
        <div
          class="absolute -right-10 -top-10 h-36 w-36 rounded-full opacity-[0.09] transition-transform duration-500 group-hover:scale-150"
          :style="{ background: course.accent }"
        />
        <div class="flex items-start justify-between gap-4">
          <div>
            <div class="flex items-center gap-2">
              <GradeBadge :value="course.exam.grade" />
              <span class="text-[12px] font-medium" style="color: var(--tk-muted)">{{ course.exam.subject }}</span>
            </div>
            <h2 class="tk-display mt-2 text-[22px] font-bold" :style="{ color: course.accent }">
              {{ course.title }}
            </h2>
            <p class="mt-1.5 text-[13.5px] leading-relaxed" style="color: var(--tk-muted)">{{ course.tagline }}</p>
            <div class="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-[12.5px]" style="color: var(--tk-muted)">
              <span>依据《{{ course.textbook.title }}》</span>
              <span>· {{ course.textbook.chapters_total }} 章 {{ sections.length }} 节 · 已拿下 {{ done }} 节</span>
            </div>
          </div>
          <ProgressRing :value="avg" :size="64" :stroke="7" :color="course.accent">
            <span class="text-[13px] font-bold" :style="{ color: course.accent }">
              {{ Math.round(avg * 100) }}%
            </span>
          </ProgressRing>
        </div>
        <div class="mt-4 flex items-center gap-1 text-[13px] font-semibold accent-fg">
          进入学习 <ArrowRight :size="15" class="transition-transform group-hover:translate-x-1" />
        </div>
      </motion.button>
    </section>

    <!-- 真题与战况入口 -->
    <section class="grid gap-5 sm:grid-cols-2">
      <button
        type="button"
        class="tk-card tk-card-hover flex items-center gap-4 p-5 text-left"
        @click="go({ kind: 'past' })"
      >
        <span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-violet-500 to-purple-600 text-white shadow-lg">
          <ScrollText :size="22" />
        </span>
        <span>
          <span class="block font-bold">历年真题演练</span>
          <span class="block text-[13px]" style="color: var(--tk-muted)">2010–2020 十一卷整卷练习,作答计入掌握度</span>
        </span>
      </button>
      <button
        type="button"
        class="tk-card tk-card-hover flex items-center gap-4 p-5 text-left"
        @click="go({ kind: 'dashboard' })"
      >
        <span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 text-white shadow-lg">
          <Gauge :size="22" />
        </span>
        <span>
          <span class="block font-bold">掌握度战况</span>
          <span class="block text-[13px]" style="color: var(--tk-muted)">
            共 {{ allSections().length }} 节 · 全部由作答记录派生
          </span>
        </span>
      </button>
    </section>
  </div>
</template>
